# Generated by Django 4.2.4 on 2023-08-04 11:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания объекта')),
                ('code', models.CharField(default='Код нового справочника', max_length=100, unique=True, verbose_name='Код справочника')),
                ('name', models.CharField(default='Наименование справочника', max_length=300, verbose_name='Наименование справочника')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания объекта')),
                ('version', models.CharField(default='Версия справочника', max_length=50, verbose_name='Версия справочника')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата начала действия версии')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.guides', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Версия справочника',
                'verbose_name_plural': 'Версии справочников',
                'unique_together': {('guide', 'version', 'date_start')},
            },
        ),
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('object_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания объекта')),
                ('code', models.CharField(default='Код элемента', max_length=100, verbose_name='Код элемента')),
                ('value', models.CharField(default='Значение элемента', max_length=300, verbose_name='Значение элемента')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.versions', verbose_name='Версия справочника')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочников',
                'unique_together': {('version', 'code')},
            },
        ),
    ]
