# Generated by Django 4.2.4 on 2023-08-04 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versions',
            name='date_start',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала действия версии'),
        ),
    ]
